# Generated by Django 3.2.5 on 2021-07-13 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datetime_start', models.DateTimeField()),
                ('time_end', models.TimeField(blank=True, default='23:59:59', null=True)),
                ('remind_unit', models.IntegerField(blank=True, choices=[(60, 'minutes'), (3600, 'hours'), (86400, 'days'), (604800, 'weeks')], null=True)),
                ('number_of_remind_units', models.SmallIntegerField(default=1)),
                ('remind_time', models.DateTimeField(blank=True, null=True)),
                ('reminded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
